In [1]:
import numpy

In [2]:
numpy.__version__

'1.21.5'

In [3]:
import numpy as np
np.__version__

'1.21.5'

In [4]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [5]:
np.random.randint(0, 10)

8

In [6]:
np.random.randint(0, 10, 10)

array([7, 8, 1, 7, 6, 5, 1, 4, 8, 4])

In [7]:
np.random.random((3,5))

array([[0.02782855, 0.77124957, 0.80175151, 0.2823391 , 0.66724537],
       [0.22509327, 0.00481304, 0.85438572, 0.75666481, 0.25227701],
       [0.74379028, 0.00179089, 0.08980151, 0.71321165, 0.37727766]])

In [8]:
np.random.normal(10, 100, (3, 5))

array([[ 107.67823711,  109.86890152,  -56.94370647,   -9.00242254,
         -13.17414822],
       [ 118.25981848,  -74.47371639,  157.98547965,   61.48604856,
          36.35571011],
       [-147.1931629 ,  -35.1709793 ,  191.15541288,   -6.92833572,
          19.3973345 ]])

In [ ]:
np.zeros(10)

合并操作

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [ ]:
np.concatenate([x, y])

In [ ]:
z = np.array([777, 777, 888])

In [ ]:
np.concatenate([x, y, z])

合并操作

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [ ]:
np.concatenate([x, y])

In [ ]:
z = np.array([777, 777, 888])

In [ ]:
np.concatenate([x, y, z])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

合并操作

In [10]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [11]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [12]:
z = np.array([777, 777, 888])

In [14]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 777, 777, 888])