矩阵聚合

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, size=1000000)

In [3]:
np.mean(x)

-0.0006690488106234836

In [4]:
np.std(x)

0.9996366736002517

In [5]:
np.min(x)

-4.7153371714613685

In [6]:
np.argmin(x)

838575

In [7]:
x[838575]

-4.7153371714613685

In [8]:
x = np.arange(16)

In [9]:
np.random.shuffle(x)
x

array([ 9, 13,  1,  4, 12,  3,  7,  8, 14,  6,  0, 11, 15, 10,  5,  2])

In [10]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
x

array([ 9, 13,  1,  4, 12,  3,  7,  8, 14,  6,  0, 11, 15, 10,  5,  2])

In [12]:
x.sort()

In [13]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

fancy indexing

In [14]:
ind = [3,5,8]

In [15]:
x[ind]

array([3, 5, 8])

In [16]:
np.random.shuffle(x)

In [17]:
x[ind]

array([14,  9, 11])

In [18]:
x

array([ 0,  8, 12, 14,  1,  9, 13, 10, 11,  3,  5,  2,  4, 15,  7,  6])

In [19]:
ind = np.array([
    [0,2],
    [1,3]
])

In [20]:
x[ind]

array([[ 0, 12],
       [ 8, 14]])

numpy.array比较

In [21]:
x

array([ 0,  8, 12, 14,  1,  9, 13, 10, 11,  3,  5,  2,  4, 15,  7,  6])

In [22]:
x < 3

array([ True, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False])